name: Kicking Video
favicon: null
layout_spectrum: 0.17741
typography_spectrum: 0.4046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0397d6'
    - '#000000'
    - '#ffffff'
    - '#4f4f4f'
    - '#00ffff'
  brandStrength: 0.3125
  lightness: 0.6625868326518685
  saturation: 0.4298704657703638
  rhythmicContrast: 0.9314987587276846
purpose: []
