name: Kicking Video
favicon: null
layout_spectrum: 0.44438071991316974
typography_spectrum: 0.15701783634722233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.22135504544712603
  lightness: 0.6625868326518685
  saturation: 0.4298704657703638
  rhythmicContrast: 0.9314987587276846
purpose: []
